---
baseURL: https://example.com
languageCode: en-us
title: Project Alocaust
pygmentsstyle: monokai
module:
  imports:
  - path: github.com/forestryio/hugo-theme-novela
paginate: "6"
social:
  twitter: https://twitter.com/215return
  github: https://github.com/return215
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
